### ISSUE TITLE
Add Language_ja.properties の300行目付近の訳について

### ISSUE THREAD

**Issue by koizumistr** [KoukiHama/sw360#1]
例えば
do.you.really.want.to.remove.the.link.to.project.x=あなたは本当にプロジェクトへのリンクを削除しますか ＜b data-name="project"＞＜/b＞?
とリンク？を最後に持ってきているものがありますが、その上では
do.you.really.want.to.delete.the.release.x=本当にリリース ＜b data-name="name"＞ を削除しますか？
とリンク？が文中に埋め込まれています。
後者に揃えるべきかと思います。
（すみません、実際に表示した結果を見ていないので、たとえば「このように訳し分けた方が表示した場合にはきれいに見える」みたいな工夫なら、上記の指摘は無視してください。）

**Comment by KoukiHama** [comment]
Issueありがとうございます。表示結果確認の上で対応したものもあるのですが、上記例は未確認でした。確認の上で対応します。あと、基本的に後者例で揃えますね。

**Comment by KoukiHama** [comment]
表示を確認し，プルリクしました
ありがとうございました．

https://github.com/eclipse/sw360/pull/937
