### ISSUE TITLE
Language_ja.properties の871行目付近の文字列について

### ISSUE THREAD

**Issue by fu7mu4** [KoukiHama/sw360#4]
addJapanese ブランチの frontend/sw360-portlet/src/main/resources/content/Language_ja.properties ファイルの871行目の項目に,が使用されていますがピリオドではないでしょうか? 問題ないかご確認ください。

現状

```
remarks.additional.requirements=備考 追加要件
removed.project,links=プロジェクトリンクの削除
removed.release.links=リリースリンクの削除
```

修正案

```
remarks.additional.requirements=備考 追加要件
removed.project.links=プロジェクトリンクの削除
removed.release.links=リリースリンクの削除
```

**Comment by KoukiHama** [comment]
対応済．ありがとうございました．以下でプルリクエストいたしました．
https://github.com/eclipse/sw360/pull/937
