### ISSUE TITLE
CVE-SEARCHの有効化、スケジュールオフセット、インターバルが編集できない

### ISSUE THREAD

**Issue by yyosioka** [KoukiHama/sw360#58]
### Description

CVE-SEARCHの有効化、スケジュールオフセット、インターバルが編集できない
どうやったら編集できるかを教えていただきたいです。

#### How to reproduce

以下のページに従ってDocker環境を構築
https://github.com/eclipse/sw360/blob/master/README_DOCKER.md

1 git clone https://github.com/eclipse/sw360.git
2 cd sw360
3 ./docker_build.sh
4  docker-compose up 

CVE-Search-Dockerをインストール
 5 git clone https://github.com/cve-search/CVE-Search-Docker.git
 6 cd CVE-Search-Docker
 7 docker-compose up 

8 SW360のAdminから設定しようとしましたがスケジュールオフセット、インターバルが編集できない
　

#### Screenshots

![スクリーンショット 2022-04-14 155151](https://user-images.githubusercontent.com/62535924/163335846-17b32272-c885-4a58-bf04-aab7449938ec.png)

### Versions

2022/4/7 latest acquisition

**Comment by KoukiHama** [comment]
@yyosioka  現在，GUIからCVEサーバを設定する方法はありません．
設定ファイルを編集し，指定します．

Dockerでインストールした場合は，一度SW360の動くコンテナの中にはいり

以下の設定ファイルの

tomcat-9.0.33/webapps/cvesearch/WEB-INF/classes/cvesearch.properties

以下のパラメータをお手元の，CVEサーバに変えることで取得できます
(tomcatの再起動は必要)

>cvesearch.host=

あるいは，公開サーバの以下を設定しても情報取得可能です．

 https://cvepremium.circl.lu/

**Comment by yyosioka** [comment]
@KoukiHama 

回答ありがとうございます。確認します。

**Comment by yyosioka** [comment]
@KoukiHama 

sw360 Dockerの中に入って

以下のファイル
/app/sw360/tomcat-9.0.33/webapps/schedule/WEB-INF/classes
sw360.properties

以下の値を編集しました
schedule.cvesearch.interval.seconds = 300
autostart = cvesearchService

その後Dockerを再起動すると画面にも結果が反映されました。

ご協力ありがとうございます。
