### ISSUE TITLE
SW360　cvesearchの処理内容について質問させてください。

### ISSUE THREAD

**Issue by yyosioka** [KoukiHama/sw360#75]
SW360　cvesearchの処理内容について質問させてください。

CVE-SEARCHの処理で Level 2、 Level 3の処理が実装されていますが、実装されている内容はわかりますが
具体的にどういうユースケースを想定しているのでしょうか。

 Level 2 推測されるベンダーと製品のバージョンで検索
 Level 3 バージョンを指定せずに、推測されるベンダーや製品で検索する。

ソースコードいうと以下の部分処理になります。
sw360-sw360-16.0.0-M1\sw360-sw360-16.0.0-M1\backend\src\src-cvesearch\src\main\java\org\eclipse\sw360\cvesearch\datasource\heuristics\SearchLevels.java
    private void addGuessingSearchLevels(CveSearchApi cveSearchApi, int vendorThreshold, int productThreshold, int cutoff) {

**Comment by KoukiHama** [comment]
時間を見つけて補足情報追記いたします。
まずは、以下が参考になるかもしれません
https://www.eclipse.org/sw360/docs/userguide/vulnerabilitymanagement/#automatic-update-of-vulnerabilities

**Comment by yyosioka** [comment]
早急な回答ありがとうございます。なるほど不完全なCPE IDを入れた場合にも検索ができるんですね。

**Comment by yyosioka** [comment]
本件回答いただいたのでクローズします。
