### ISSUE TITLE
プロジェクトに含まれているリリースのエクスポート機能について

### ISSUE THREAD

**Issue by yyosioka** [KoukiHama/sw360#77]
sw360-17.0.1-M1まで確認しましたが、プロジェクトに含まれている
リリースの情報をSPDX等のファイル形式で出力する機能がありません。
対応する予定等がございましたらご教授ください。

**Comment by KoukiHama** [comment]
![image](https://github.com/KoukiHama/sw360/assets/39894802/19647429-8edf-447c-92f2-5725886ea395)

プロジェクトに含まれるリリース情報等は上記のProject License Clearing からスプレッドシートで出力可能です。
また、SPDXやCycloneDXでの出力は順次対応中で、最新版だとビルド時にオプションを有効することで一部利用できるようになっています。

**Comment by yyosioka** [comment]
> プロジェクトに含まれるリリース情報等は上記のProject License Clearing からスプレッドシートで出力可能です。

Project License Clearing からスプレッドシートで出力可能とのこと承知しました。
こちらでも確認します。

> また、SPDXやCycloneDXでの出力は順次対応中で、最新版だとビルド時にオプションを有効することで一部利用できるようになっています

上記最新版はsw360-17.0.1-M1でよろしいでしょうか。
また、ビルド時のオプションもご教授いただけないでしょうか。

**Comment by yyosioka** [comment]
@KoukiHama 

お手数ですが以下に回答いただけないでしょうか。
上記最新版はsw360-17.0.1-M1でよろしいでしょうか。
また、ビルド時のオプションもご教授いただけないでしょうか。

**Comment by KoukiHama** [comment]
最新のバージョンというのはMasterBranchのヘッドという意味でした。誤解を招く書き方をしてしまいすみません。

SBOM関連オプションは以下です

https://github.com/eclipse-sw360/sw360/blob/b58f28c317fad35b4d3e35f17a1d8a107adcca7c/frontend/sw360-portlet/src/main/resources/sw360.properties#L253


https://github.com/eclipse-sw360/sw360/blob/b58f28c317fad35b4d3e35f17a1d8a107adcca7c/frontend/sw360-portlet/src/main/resources/sw360.properties#L258

**Comment by yyosioka** [comment]
回答いただいたので、本件Closeします。
